server:
  port: 5000 # 실제 서버 배포 시 5000번 포트를 사용
  servlet:
    encoding:
      charset: utf-8

spring:
  datasource:
    url: jdbc:mysql://${rds.hostname}:${rds.port}/${rds.db.name}
    driver-class-name: com.mysql.jdbc.Driver
    username: ${rds.username}
    password: ${rds.password}

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  messages:
    basename: i18n/exception
    encoding: UTF-8

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${google.client.id}
            client-secret: ${google.client.secret}
            scope: ${google.scope}

  # 파일 업로드 크기 설정
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

jwt:
  secret: ${jwt.secret}

# cors 설정
cors:
  allowed-origins: 'http://localhost:3000'
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: '*'
  max-age: 3600

# 토큰 관련 secret Key 및 RedirectUri 설정
app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpiry: 120000
    refreshTokenExpiry: 604800000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth/redirect
      - http://localhost:8080/test
      - http://localhost:8080/login/google
      - http://localhost:8080/join
      - http://devin-env.eba-ydykqmma.ap-northeast-2.elasticbeanstalk.com/join
      - http://devin-env.eba-ydykqmma.ap-northeast-2.elasticbeanstalk.com/login/google
      - http://devin-env.eba-ydykqmma.ap-northeast-2.elasticbeanstalk.com/login/oauth2/code/google
      - http://devin-env.eba-ydykqmma.ap-northeast-2.elasticbeanstalk.com/test

logging.level:
  org.hibernate.SQL: INFO

# AWS S3 관련 설정
cloud:
  aws:
    credentials:
      access-key: ${iam.access.key}
      secret-key: ${iam.secret.key}
    region:
      static: ap-northeast-2
    s3:
      bucket: ${s3.bucket.name}
    stack:
      auto: false

# Swagger
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /**